logging:
  level:
    love:
      forte:
        simbot: debug
# h2数据库的网页控制台 localhost:8080/h2-console
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/Jx3_Bot
    username: sa
    password: 123456
  h2:
    console:
      enabled: true
simbot:
  core:
    # 扫描 simbot-bots目录下的所有 .bot 文件。
    bot-resource-type: RESOURCE_FIRST
#  component:
#    mirai:
#      device-info-file: file:./device-info/device.json
jx3sp:
  account: jx3sp账号
  password: 密码

