logging:
  level:
    love:
      forte:
        simbot: debug

simbot:
  core:
    # 扫描 simbot-bots目录下的所有 .bot 文件。
    bot-resource-type: RESOURCE_FIRST
jx3sp:
  account: 1062589920@qq.com
  password: lyh750802
#code=744302716
#password=nimasile666666
#  code=2468158366
#  password=aaa111111
